/**
 * Seed Trailer Data
 *
 * Hardcoded trailers from known sources for demo/fallback.
 * Used when TMDB/YouTube API keys are not configured.
 *
 * All trailers are from official studio channels on YouTube.
 * Source URLs provided for attribution.
 */

export interface SeedTrailer {
  title: string
  description: string
  release_year: number
  genre: string
  studio: string
  duration_secs: number
  trailer_type: string
  source_name: string
  source_url: string
  source_type: string
  thumbnail_url: string
  is_featured: boolean
}

export const SEED_TRAILERS: SeedTrailer[] = [
  {
    title: 'Dune: Part Two',
    description: 'Paul Atreides unites with the Fremen to seek revenge against those who destroyed his family.',
    release_year: 2024,
    genre: 'sci-fi',
    studio: 'Warner Bros. Pictures',
    duration_secs: 155,
    trailer_type: 'official',
    source_name: 'Warner Bros. Pictures',
    source_url: 'https://www.youtube.com/watch?v=Way9Dexny3w',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/Way9Dexny3w/maxresdefault.jpg',
    is_featured: true,
  },
  {
    title: 'Deadpool & Wolverine',
    description: 'The merc with a mouth teams up with the clawed mutant in a multiverse adventure.',
    release_year: 2024,
    genre: 'action',
    studio: 'Marvel Studios',
    duration_secs: 142,
    trailer_type: 'official',
    source_name: 'Marvel Entertainment',
    source_url: 'https://www.youtube.com/watch?v=73_1biulkYk',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/73_1biulkYk/maxresdefault.jpg',
    is_featured: true,
  },
  {
    title: 'The Batman Part II',
    description: 'The Dark Knight returns to investigate a new string of crimes in Gotham City.',
    release_year: 2026,
    genre: 'action',
    studio: 'Warner Bros. Pictures',
    duration_secs: 0,
    trailer_type: 'teaser',
    source_name: 'Warner Bros. Pictures',
    source_url: 'https://www.youtube.com/watch?v=8_nlGQHlRFU',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/8_nlGQHlRFU/maxresdefault.jpg',
    is_featured: true,
  },
  {
    title: 'Inside Out 2',
    description: 'Follow Riley in her teenage years as new emotions join the mix inside her mind.',
    release_year: 2024,
    genre: 'animation',
    studio: 'Pixar Animation Studios',
    duration_secs: 100,
    trailer_type: 'official',
    source_name: 'Pixar',
    source_url: 'https://www.youtube.com/watch?v=LEjhY15eCx0',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/LEjhY15eCx0/maxresdefault.jpg',
    is_featured: true,
  },
  {
    title: 'Godzilla x Kong: The New Empire',
    description: 'Godzilla and Kong team up against a colossal threat hidden deep within the Earth.',
    release_year: 2024,
    genre: 'action',
    studio: 'Legendary Pictures',
    duration_secs: 135,
    trailer_type: 'official',
    source_name: 'Warner Bros. Pictures',
    source_url: 'https://www.youtube.com/watch?v=qqrpMRDuPfc',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/qqrpMRDuPfc/maxresdefault.jpg',
    is_featured: false,
  },
  {
    title: 'Oppenheimer',
    description: 'The story of J. Robert Oppenheimer and the development of the atomic bomb.',
    release_year: 2023,
    genre: 'drama',
    studio: 'Universal Pictures',
    duration_secs: 180,
    trailer_type: 'official',
    source_name: 'Universal Pictures',
    source_url: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/uYPbbksJxIg/maxresdefault.jpg',
    is_featured: false,
  },
  {
    title: 'The Fall Guy',
    description: 'A retired stuntman returns to find a missing movie star and save his ex-girlfriend\'s film.',
    release_year: 2024,
    genre: 'action',
    studio: 'Universal Pictures',
    duration_secs: 126,
    trailer_type: 'official',
    source_name: 'Universal Pictures',
    source_url: 'https://www.youtube.com/watch?v=j7jPnwVGdZ8',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/j7jPnwVGdZ8/maxresdefault.jpg',
    is_featured: false,
  },
  {
    title: 'Kingdom of the Planet of the Apes',
    description: 'Many years after the war, a young ape goes on a journey that will lead him to question everything.',
    release_year: 2024,
    genre: 'sci-fi',
    studio: '20th Century Studios',
    duration_secs: 145,
    trailer_type: 'official',
    source_name: '20th Century Studios',
    source_url: 'https://www.youtube.com/watch?v=Xlt9GZxWBiU',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/Xlt9GZxWBiU/maxresdefault.jpg',
    is_featured: false,
  },
  {
    title: 'Furiosa: A Mad Max Saga',
    description: 'The origin story of the fierce warrior Imperator Furiosa before her encounter with Max.',
    release_year: 2024,
    genre: 'action',
    studio: 'Warner Bros. Pictures',
    duration_secs: 148,
    trailer_type: 'official',
    source_name: 'Warner Bros. Pictures',
    source_url: 'https://www.youtube.com/watch?v=XJMuhwVlca4',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/XJMuhwVlca4/maxresdefault.jpg',
    is_featured: false,
  },
  {
    title: 'The Super Mario Bros. Movie',
    description: 'Brooklyn plumbers Mario and Luigi must save the Mushroom Kingdom from Bowser.',
    release_year: 2023,
    genre: 'animation',
    studio: 'Illumination',
    duration_secs: 92,
    trailer_type: 'official',
    source_name: 'Illumination',
    source_url: 'https://www.youtube.com/watch?v=TnGl01FkMMY',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/TnGl01FkMMY/maxresdefault.jpg',
    is_featured: false,
  },
  {
    title: 'John Wick: Chapter 4',
    description: 'John Wick uncovers a path to defeating the High Table. But before he can earn his freedom, he must face a new enemy with powerful alliances.',
    release_year: 2023,
    genre: 'action',
    studio: 'Lionsgate',
    duration_secs: 169,
    trailer_type: 'official',
    source_name: 'Lionsgate Movies',
    source_url: 'https://www.youtube.com/watch?v=qyUxZeN1PjA',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/qyUxZeN1PjA/maxresdefault.jpg',
    is_featured: false,
  },
  {
    title: 'Evil Dead Rise',
    description: 'A reunion between two estranged sisters is cut short by the rise of flesh-possessing demons.',
    release_year: 2023,
    genre: 'horror',
    studio: 'Warner Bros. Pictures',
    duration_secs: 96,
    trailer_type: 'official',
    source_name: 'Warner Bros. Pictures',
    source_url: 'https://www.youtube.com/watch?v=BqQNO7BzN08',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/BqQNO7BzN08/maxresdefault.jpg',
    is_featured: false,
  },
  {
    title: 'Everything Everywhere All at Once',
    description: 'An aging Chinese immigrant is swept up in an insane adventure where she alone can save the world.',
    release_year: 2022,
    genre: 'sci-fi',
    studio: 'A24',
    duration_secs: 139,
    trailer_type: 'official',
    source_name: 'A24',
    source_url: 'https://www.youtube.com/watch?v=wxN1T1uxQ2g',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/wxN1T1uxQ2g/maxresdefault.jpg',
    is_featured: false,
  },
  {
    title: 'Spider-Man: Across the Spider-Verse',
    description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People.',
    release_year: 2023,
    genre: 'animation',
    studio: 'Sony Pictures',
    duration_secs: 140,
    trailer_type: 'official',
    source_name: 'Sony Pictures',
    source_url: 'https://www.youtube.com/watch?v=shW9i6k8cB0',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/shW9i6k8cB0/maxresdefault.jpg',
    is_featured: false,
  },
  {
    title: 'Poor Things',
    description: 'The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life.',
    release_year: 2023,
    genre: 'comedy',
    studio: 'Searchlight Pictures',
    duration_secs: 141,
    trailer_type: 'official',
    source_name: 'Searchlight Pictures',
    source_url: 'https://www.youtube.com/watch?v=RlbR5N6D2Nk',
    source_type: 'youtube',
    thumbnail_url: 'https://i.ytimg.com/vi/RlbR5N6D2Nk/maxresdefault.jpg',
    is_featured: false,
  },
]
